### ISSUE TITLE
add .net example

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops-examples#47]
https://github.com/nanovms/nanos/issues/1124

```
eyberg@s1:~/myApp/bin/Release/netcoreapp2.2/linux-x64$ cat config.json
{
  "Files": ["/lib/x86_64-linux-gnu/librt.so.1", "/usr/lib/x86_64-linux-gnu/libicuuc.so.52.1", "/usr/lib/x86_64-linux-gnu/libicui18n.so.52.1", "/usr/lib/x86_64-linux-gnu/libicudata.so.52"],
  "MapDirs": {"publish/*": "/" },
  "Dirs": ["publish"],
  "Env": {
    "COMPlus_EnableDiagnostics": "0"
  }
}
```

```
eyberg@s1:~/myApp/bin/Release/netcoreapp2.2/linux-x64$ ops run -c config.json publish/myApp
booting /home/eyberg/.ops/images/myApp.img ...
assigned: 10.0.2.15
Hello World!
exit status 1
```

**Comment by eyberg** [comment]
https://github.com/nanovms/ops-examples/pull/50

**Comment by am11** [comment]
I installed the latest .NET 5 https://dotnet.microsoft.com/download/dotnet/5.0 (x64 tar.gz under `Binaries` column):

```sh
# installation
$ mkdir ~/.dotnet5
$ # curl -sSLO https://download.visualstudio.microsoft.com/download/pr/7f736160-9f34-4595-8d72-13630c437aef/b9c4513afb0f8872eb95793c70ac52f6/dotnet-sdk-5.0.102-linux-x64.tar.gz
$ tar xzf dotnet-sdk-5.0.102-linux-x64.tar.gz -C ~/.dotnet5
$ export PATH=$PATH:~/.dotnet5

$ dotnet --version
5.0.102
```


then created the app and published as a [self-contained, singlefile ELF executable](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file).
```sh
# create a new console app  'myapp1'
$ dotnet new console --name myapp1
$ cd myapp1

# publish as single-file
$ dotnet publish -c Release -r linux-x64 --self-contained true -p:PublishSingleFile=true

# check ELF'ness
$ cd bin/Release/net5.0/linux-x64/publish/
$ file myapp1 | fold
myapp1: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically
 linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[
sha1]=42c923debe410c089a93997a66ef968f8574a077, stripped, too many notes (256)

# note: this shows as shared object instead of executable because the binaries are compiled with -pie: https://github.com/dotnet/runtime/blob/45287ed696a4bea906cc15a4bc870960a4b0e623/eng/native/configureplatform.cmake#L387
# this is interesting because `ops-run` with `--debug` errors out from: https://github.com/nanovms/ops/blob/739086e34911dfea02af4d8d11e5345b82a2612c/cmd/run.go#L198

# run the app
$ ./myapp1
Hello World!
```

created a ops config:
```sh
$ cat > config.json <<EOF
{
  "Files": [
    "/lib/x86_64-linux-gnu/librt.so.1",
    "/usr/lib/x86_64-linux-gnu/libicuuc.so.60.2",
    "/usr/lib/x86_64-linux-gnu/libicui18n.so.60.2",
    "/usr/lib/x86_64-linux-gnu/libicudata.so.60.2",
    "/usr/lib/x86_64-linux-gnu/libssl.so.1.1",
    "/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1",
    "/lib/x86_64-linux-gnu/libpthread.so.0",
    "/usr/lib/x86_64-linux-gnu/libnuma.so.1",
    "/usr/lib/x86_64-linux-gnu/libnuma.so.1.0.0"
  ],
  "Env": {
    "COMPlus_EnableDiagnostics": "0"
  }
}
EOF
```
(had to add libssl and its dependencies; libnuma is optional)

then executed with ops-run:

```sh
$ ops run ./myapp1 -c ./config.json
[myapp1]
booting /home/am11/.ops/images/myapp1.img ...
You specified hardware acceleration, but it is not supported
Are you running inside a vm? If so disable accel with --accel=false

assigned: 10.0.2.15
Failed to create CoreCLR, HRESULT: 0x80004005
exit status 19
```

with `--trace` passed to ops-run, it shows:

```
1 membarrier
1 nosyscall membarrier
1 run thread, cpu 0, frame 0xffff800002400400, rip 0x17291b639, rsp 0x7fcd86c8, rdi 0x0, rax 0xffffffffffffffda, rflags 0x246, cs 0x2b, sysret
1 mmap
1 mmap: addr 0x0000000000000000, length 0x1000, prot 0x3, flags 0x22, fd -1, offset 0x0
1    alloc: 0x1b7ee8000

1    anonymous, specified target 0x1b7ee8000
1    returning 0x1b7ee8000
1 direct return: 7380828160, rsp 0x7fcd8698
1 run thread, cpu 0, frame 0xffff800002400400, rip 0x17291b813, rsp 0x7fcd8698, rdi 0x0, rax 0x1b7ee8000, rflags 0x246, cs 0x2b, sysret
1 mlock
1 direct return: 0, rsp 0x7fcd86c8
1 run thread, cpu 0, frame 0xffff800002400400, rip 0x17291ba47, rsp 0x7fcd86c8, rdi 0x1b7ee8000, rax 0x0, rflags 0x213, cs 0x2b, sysret
1 run thread, cpu 0, frame 0xffff800002400400, rip 0x1728b0ce0, rsp 0x7fcd8368, rdi 0x1454400, rax 0x144dac0, rflags 0x202, cs 0x2b, iret
1 run thread, cpu 0, frame 0xffff800002400400, rip 0x1728909e0, rsp 0x7fcd8568, rdi 0x172bebc40, rax 0x1, rflags 0x202, cs 0x2b, iret
1 mprotect
1 mprotect: addr 0x00000000008e2000, len 0x1000, prot 0x7
1 vmap_update_protections: validate [0x8e2000 0x8e3000)
1 direct return: -13, rsp 0x7fcd8568
1 run thread, cpu 0, frame 0xffff800002400400, rip 0x17291b8e7, rsp 0x7fcd8568, rdi 0x8e2000, rax 0xfffffffffffffff3, rflags 0x246, cs 0x2b, sysret
1 run thread, cpu 0, frame 0xffff800002400400, rip 0x16f810820, rsp 0x7fcd8558, rdi 0x1453da0, rax 0x1453d40, rflags 0x202, cs 0x2b, iret
1 run thread, cpu 0, frame 0xffff800002400400, rip 0x16f80f120, rsp 0x7fcd7fe8, rdi 0x7fcd81b0, rax 0x4000000000000000, rflags 0x206, cs 0x2b, iret
1 run thread, cpu 0, frame 0xffff800002400400, rip 0x16f812a40, rsp 0x7fcd7f78, rdi 0x16f81085d, rax 0x0, rflags 0x206, cs 0x2b, iret
1 run thread, cpu 0, frame 0xffff800002400400, rip 0x16f8117f0, rsp 0x7fcd7e58, rdi 0x7fcd7e80, rax 0x1764a4750, rflags 0x213, cs 0x2b, iret
1 run thread, cpu 0, frame 0xffff800002400400, rip 0x16f811918, rsp 0x7fcd7dd0, rdi 0x16f8001c8, rax 0x16fa17200, rflags 0x202, cs 0x2b, iret
1 run thread, cpu 0, frame 0xffff800002400400, rip 0x16f811bad, rsp 0x7fcd7dd0, rdi 0xc5, rax 0x16f813f40, rflags 0x206, cs 0x2b, iret
1 run thread, cpu 0, frame 0xffff800002400400, rip 0x16f811c21, rsp 0x7fcd7dd0, rdi 0xa0, rax 0x16f813f40, rflags 0x202, cs 0x2b, iret
1 run thread, cpu 0, frame 0xffff800002400400, rip 0x16f80e7d0, rsp 0x7fcd7f78, rdi 0x16f814581, rax 0x14, rflags 0x206, cs 0x2b, iret
1 futex
1 futex_wake [1 0x000000016fa171a0 2] 2147483647
1 direct return: 0, rsp 0x7fcd7fa0
1 run thread, cpu 0, frame 0xffff800002400400, rip 0x15f80f92e, rsp 0x7fcd7fa0, rdi 0x16fa171a0, rax 0x0, rflags 0x246, cs 0x2b, sysret
1 run thread, cpu 0, frame 0xffff800002400400, rip 0x16f811918, rsp 0x7fcd7f90, rdi 0x1f4c00200, rax 0x16fa17230, rflags 0x202, cs 0x2b, iret
1 run thread, cpu 0, frame 0xffff800002400400, rip 0x16f811bad, rsp 0x7fcd7f90, rdi 0xfe1, rax 0x1f4d43f88, rflags 0x206, cs 0x2b, iret
1 run thread, cpu 0, frame 0xffff800002400400, rip 0x16f811bc9, rsp 0x7fcd7f90, rdi 0xfe1, rax 0x1f4d43f88, rflags 0x207, cs 0x2b, iret
1 run thread, cpu 0, frame 0xffff800002400400, rip 0x16f811be1, rsp 0x7fcd7f90, rdi 0xfe1, rax 0x1f4d43f88, rflags 0x202, cs 0x2b, iret
1 run thread, cpu 0, frame 0xffff800002400400, rip 0x16f811be1, rsp 0x7fcd7f90, rdi 0x1f4cb64f0, rax 0x1f4d43f88, rflags 0x206, cs 0x2b, iret
1 run thread, cpu 0, frame 0xffff800002400400, rip 0x16f811c21, rsp 0x7fcd7f90, rdi 0x1b9, rax 0x1f4d43f88, rflags 0x212, cs 0x2b, iret
1 run thread, cpu 0, frame 0xffff800002400400, rip 0x1f4c91e55, rsp 0x7fcd80a0, rdi 0x1, rax 0x0, rflags 0x297, cs 0x2b, iret
1 run thread, cpu 0, frame 0xffff800002400400, rip 0x172888950, rsp 0x7fcd87b8, rdi 0x0, rax 0x7fcd87c0, rflags 0x246, cs 0x2b, iret
1 run thread, cpu 0, frame 0xffff800002400400, rip 0x17285b490, rsp 0x7fcd8648, rdi 0x7fcd8650, rax 0xfbad8001, rflags 0x206, cs 0x2b, iret
1 run thread, cpu 0, frame 0xffff800002400400, rip 0x17285b77a, rsp 0x7fcd80d0, rdi 0x7fcd8765, rax 0x38, rflags 0x202, cs 0x2b, iret
1 run thread, cpu 0, frame 0xffff800002400400, rip 0x17285c630, rsp 0x7fcd80d0, rdi 0x7fcd8765, rax 0x17285c630, rflags 0x202, cs 0x2b, iret
1 run thread, cpu 0, frame 0xffff800002400400, rip 0x17285d140, rsp 0x7fcd80d0, rdi 0x7fcd8765, rax 0x8, rflags 0x246, cs 0x2b, iret
1 run thread, cpu 0, frame 0xffff800002400400, rip 0x1728588b0, rsp 0x7fcd80c8, rdi 0x80004005, rax 0x80004005, rflags 0x246, cs 0x2b, iret
1 run thread, cpu 0, frame 0xffff800002400400, rip 0x17288ba00, rsp 0x7fcd8788, rdi 0x172bec680, rax 0xd68, rflags 0x206, cs 0x2b, iret
1 write
Failed to create CoreCLR, HRESULT: 0x800040051 direct return: 45, rsp 0x7fcd86e0
1 run thread, cpu 0, frame 0xffff800002400400, rip 0x172910257, rsp 0x7fcd86e0, rdi 0x2, rax 0x2d, rflags 0x293, cs 0x2b, sysret
1 write
```
(full log available at: http://sprunge.us/l8gdy5)
that `-13` is `EACCESS` emerging from: https://github.com/nanovms/nanos/blob/9b43cfc/src/unix/mmap.c#L554.

**Comment by eyberg** [comment]
cc @francescolavra - can you take a look at this?

**Comment by francescolavra** [comment]
https://github.com/nanovms/nanos/pull/1415 fixes the issue in Nanos. @am11 in config.json I had to remove the `.2` suffix from the `/usr/lib/x86_64-linux-gnu/libicu*` file entries, otherwise .NET would fail with `Couldn't find a valid ICU package installed on the system`.

**Comment by am11** [comment]
@francescolavra, thanks. In my new Ubuntu box, i have libicuuc.so.66.1 (without `.1` are just the symlink).

I tested it with latest nanos, while it runs the app (and prints `Hello World!`), it exits with status 1.
Continuing with above steps:
```sh
$ cat ./config.json
{
  "Files": [
    "/lib/x86_64-linux-gnu/librt.so.1",
    "/usr/lib/x86_64-linux-gnu/libicuuc.so.66",
    "/usr/lib/x86_64-linux-gnu/libicui18n.so.66",
    "/usr/lib/x86_64-linux-gnu/libicudata.so.66",
    "/usr/lib/x86_64-linux-gnu/libssl.so.1.1",
    "/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1",
    "/lib/x86_64-linux-gnu/libpthread.so.0",
    "/usr/lib/x86_64-linux-gnu/libnuma.so.1",
    "/usr/lib/x86_64-linux-gnu/libnuma.so.1.0.0"
  ],
  "Env": {
    "COMPlus_EnableDiagnostics": "0"
  }
}

$ ops run ./myapp1 -c ./config.json --accel=false
booting /home/am11/.ops/images/myapp1.img ...
You have disabled hardware acceleration

en1: assigned 10.0.2.15
Hello World!
exit status 1
```

Here is the like captured `--trace` logs:

```sh
$ ~/ops/ops run ./myapp1 -c ./config.json --accel=false --trace 2>&1 | curl -F"sprunge=<-" http://sprunge.us
http://sprunge.us/VwBICY
```

lines such as:
> 1 page fault, vaddr 0x1cd0b5f18

suggests possible issue with page boundaries.

**Comment by am11** [comment]
I have noticed that node.js -based, rust and other platforms also have the same behavior with nanos (`exit status 1`), so it is probably not specific to dotnet.

**Comment by francescolavra** [comment]
@am11, that's right, exit status 1 is not specific to .NET; it does not indicate an issue, in fact it indicates that the user program exited with exit code 0 (which usually means success).
The `page fault` trace messages are expected and do not indicate an issue either.
When an user program exists with a given code `x` and the kernel makes Qemu terminate (via the isa-debug Qemu device), Qemu returns with exit code `1 | (x << 1)`, and that's where the `exit status 1` message comes from.

**Comment by am11** [comment]
Great, thanks for the explanation!

So we are good with [self-contained deployment](https://docs.microsoft.com/en-us/dotnet/core/deploying/runtime-patch-selection) (#55) and [single-file deployment](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file).

For ASP.NET Core 5.0 MVC application, I have worked out these steps for single-file deployment:

```sh
# in WSL
$ dotnet new mvc -n mymvc2; cd $_
$ dotnet publish -c Release -r linux-x64 --self-contained true -p:PublishSingleFile=true
$ cd bin/Release/net6.0/linux-x64/publish
$ cat > config.json <<EOF
{
  "Files": [
    "/lib/x86_64-linux-gnu/librt.so.1",
    "/usr/lib/x86_64-linux-gnu/libicuuc.so.66",
    "/usr/lib/x86_64-linux-gnu/libicui18n.so.66",
    "/usr/lib/x86_64-linux-gnu/libicudata.so.66",
    "/usr/lib/x86_64-linux-gnu/libssl.so.1.1",
    "/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1",
    "/lib/x86_64-linux-gnu/libpthread.so.0",
    "/usr/lib/x86_64-linux-gnu/libnuma.so.1",
    "/usr/lib/x86_64-linux-gnu/libnuma.so.1.0.0"
  ],
  "Dirs": ["./"],
  "Env": {
    "COMPlus_EnableDiagnostics": "0",
    "DOTNET_USE_POLLING_FILE_WATCHER": "1",
    "ASPNETCORE_URLS": "http://*:5000"
  }
}
EOF

$ ~/ops/ops run ./mymvc2 -p 5000 -c ./config.json --accel=false
booting /home/am11/.ops/images/mymvc2.img ...
You have disabled hardware acceleration

en1: assigned 10.0.2.15
warn: Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository[50]
      Using an in-memory repository. Keys will not be persisted to storage.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[59]
      Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {39fa733c-c9cd-40a8-9d12-2b6e969fbee0} may be persisted to storage in unencrypted form.
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /
```

Then in Windows, navigate to `http://localhost:5000/`.

Note that `DOTNET_USE_POLLING_FILE_WATCHER` is required to switch off inotify (https://github.com/nanovms/nanos/issues/884) and `ASPNETCORE_URLS` is required as kestrel server by default uses loopback interface (which works between WSL->Windows), but not in unikernel isolation. Another way is to pass `--urls http://*:5000` argument which is a bit buggy with ELF executable atm (https://github.com/nanovms/ops/issues/942).

@eyberg, this issue can be closed. (-8

**Comment by eyberg** [comment]
maybe we can re-purpose this tkt into another example https://github.com/nanovms/ops-examples/tree/master/dot-net here since there are multiple ways to deploy

**Comment by goncalo-oliveira** [comment]
This doesn't seem to work on a M1 Apple chip. Any way to work around this?

**Comment by am11** [comment]
What's the error?

**Comment by goncalo-oliveira** [comment]
The lib files (from the config) dont' exist on a Mac, I think. And apologies, should have posted the output straight away.

```bash
$ ops run -c config.json published/myapp -v --show-debug --trace 
 100% |████████████████████████████████████████|  [0s:0s]
panic: failed building manifest: file "/lib/x86_64-linux-gnu/librt.so.1" is missing: stat /lib/x86_64-linux-gnu/librt.so.1: no such file or directory

goroutine 1 [running]:
github.com/nanovms/ops/cmd.runCommandHandler(0xc00091ca00?, {0xc000476e40, 0x1, 0x6?})
	/Users/eyberg/go/src/github.com/nanovms/ops/cmd/cmd_run.go:62 +0x373
github.com/spf13/cobra.(*Command).execute(0xc00091ca00, {0xc000476de0, 0x6, 0x6})
	/Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc000906780)
	/Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	/Users/eyberg/go/src/github.com/nanovms/ops/ops.go:8 +0x1e
```

**Comment by eyberg** [comment]
so the missing libs in a config is copied from a linux host which is why ops is not finding it for you here - there are a handful of ways of going about dealing with this:

1) simplest is to build the image/package on a linux host and copy it to your mac

2) use ops built-in cross-building env - https://docs.ops.city/ops/crossbuilding (which runs a small linux host to do custom build ala docker)

3) build in docker and cp it out

4) I thought about building a custom .net package that had all the libs present but it felt to me at the time that most .net users would have versions that differed enough that wouldn't make sense (totally happy to revisit that though)

**Comment by am11** [comment]
> 3\. build in docker and cp it out

That's probably the easiest way:

```sh
$ docker run --name temp1 amd64/ubuntu sh -c 'apt update && apt install -y libnuma-dev libicu-dev libssl-dev'
$ mkdir -p rootfs/usr
$ docker cp temp1:/usr/lib rootfs/usr
$ docker cp temp1:/lib rootfs 
```

and then prefix all paths in config.json with `/path/to/pwd/rootfs`.

**Comment by goncalo-oliveira** [comment]
Thank you for the quick replies, really!

I went for the docker option, which is indeed, the simplest and fastest. I've had to change a few of the files since the versions didn't match. This is the config (I've also reordered the files for readability, don't think that matters)

```json
{
  "Files": [
    "./linux/lib/x86_64-linux-gnu/libpthread.so.0",
    "./linux/lib/x86_64-linux-gnu/librt.so.1",
    "./linux/usr/lib/x86_64-linux-gnu/libcrypto.so.3",
    "./linux/usr/lib/x86_64-linux-gnu/libicuuc.so.70",
    "./linux/usr/lib/x86_64-linux-gnu/libicui18n.so.70",
    "./linux/usr/lib/x86_64-linux-gnu/libicudata.so.70",
    "./linux/usr/lib/x86_64-linux-gnu/libnuma.so.1",
    "./linux/usr/lib/x86_64-linux-gnu/libnuma.so.1.0.0",
    "./linux/usr/lib/x86_64-linux-gnu/libssl.so.3"
  ],
  "MapDirs": {"published/*": "/" },
  "Dirs": ["published"],
  "Env": {
    "COMPlus_EnableDiagnostics": "0"
  }
}
```

I've made sure all of those files now exist and retried, but still unsuccessful. Now I get a more generic file not found.

```bash
$ ops run -c config.json published/myapp --trace
 100% |████████████████████████████████████████|  [0s:0s]
panic: failed building manifest: file does not exist

goroutine 1 [running]:
github.com/nanovms/ops/cmd.runCommandHandler(0xc000885b80?, {0xc0006e0b40, 0x1, 0x4?})
	/Users/eyberg/go/src/github.com/nanovms/ops/cmd/cmd_run.go:62 +0x373
github.com/spf13/cobra.(*Command).execute(0xc000885b80, {0xc0006e0b00, 0x4, 0x4})
	/Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc00062f900)
	/Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	/Users/eyberg/go/src/github.com/nanovms/ops/ops.go:8 +0x1e
```

The app was built to the `published` folder and it's there... Here's the exact command I used to build the app

![image](https://user-images.githubusercontent.com/2210485/212369091-2d279de9-f54a-444c-9cd3-738d211c4d58.png)

```bash
$ dotnet publish -c release --self-contained --runtime linux-x64 -o published
```

**Comment by eyberg** [comment]
1) I'd remove the './' on those file paths and i'd make sure those files actually exist in the path of 'linux/usr/lib/x86_64-linux-gnu/libssl.so.3' - (eg: did you mkdir -p linux locally on your mac? the way the config is written it is going to expect a folder of 'linux/usr/lib/x86_64-linux-gnu in the same folder you are running your config)

2) either pick MapDirs or Dirs - you prob don't want to use both for the same folder - MapDirs the way you have it will copy the contents of published and stick all of it in '/'. Dirs will include the "published" folder as is - so the effect here is that your resulting image will have 2 copies - stuff in '/' and the same in '/published'

when you are using that config locally (on your mac) ops assumes that Files, MapDirs, and Dirs all exist locally

**Comment by eyberg** [comment]
also - another thing that might be worth trying is the 'from-docker' importer - ```ops pkg from-docker dotnet/runtime``` - that would require you build your .net project inside the container first then you can copy it out (along with its deps)

**Comment by goncalo-oliveira** [comment]
> I'd remove the './' on those file paths and i'd make sure those files actually exist in the path of 'linux/usr/lib/x86_64-linux-gnu/libssl.so.3' - (eg: did you mkdir -p linux locally on your mac? the way the config is written it is going to expect a folder of 'linux/usr/lib/x86_64-linux-gnu in the same folder you are running your config)

Removing the `./` has no effect. The error doesn't seem to be related to these files (I think) because if I change the name of one of them to something that doesn't exist, I get an explicit error, but this error now is a generic file not found.
But yes, the files DO exist. To keep things simple, I created a `lib` folder in the same place the config file is located and copied the files in. I've also adjusted the config

```json
{
  "Files": [
    "lib/libpthread.so.0",
    "lib/librt.so.1",
    "lib/libcrypto.so.3",
    "lib/libicuuc.so.70",
    "lib/libicui18n.so.70",
    "lib/libicudata.so.70",
    "lib/libnuma.so.1",
    "lib/libnuma.so.1.0.0",
    "lib/libssl.so.3"
  ],
  ...
}
```

So, to make things clear

```bash
myapp
   /published
   /lib
   config.json
```

> either pick MapDirs or Dirs - you prob don't want to use both for the same folder - MapDirs the way you have it will copy the contents of published and stick all of it in '/'. Dirs will include the "published" folder as is - so the effect here is that your resulting image will have 2 copies - stuff in '/' and the same in '/published'

Ok, I removed `Dirs` and kept `MapDirs`. But for reference, I tried with both. The original config was copied from the example.

The complete config file

```json
{
  "Files": [
    "lib/libpthread.so.0",
    "lib/librt.so.1",
    "lib/libcrypto.so.3",
    "lib/libicuuc.so.70",
    "lib/libicui18n.so.70",
    "lib/libicudata.so.70",
    "lib/libnuma.so.1",
    "lib/libnuma.so.1.0.0",
    "lib/libssl.so.3"
  ],
  "MapDirs": {"published/*": "/" },
  "Env": {
    "COMPlus_EnableDiagnostics": "0"
  }
}
```

**Comment by goncalo-oliveira** [comment]
This seems to be related... https://github.com/nanovms/ops/issues/1264

**Comment by am11** [comment]
> "./linux/lib/x86_64-linux-gnu/librt.so.1",

1. docker cp to `/tmp/linux` to keep paths simple and use absolute paths in config "/tmp/linux/lib....."
2. modify this line `"MapDirs": {"published/*": "/" }` as `"MapDirs": {"published/*": "/", "/tmp/linux/*": "/" }`

**Comment by am11** [comment]
@goncalo-oliveira, after some experiments, I found a way to make it work by copying libs from container to `/tmp/linux`, and using absolute paths in `config.json`:

```json
{
    "Files": [
      "/tmp/linux/lib/x86_64-linux-gnu/librt.so.1",
      "/tmp/linux/usr/lib/x86_64-linux-gnu/libicuuc.so.70.1",
      "/tmp/linux/usr/lib/x86_64-linux-gnu/libicui18n.so.70.1",
      "/tmp/linux/usr/lib/x86_64-linux-gnu/libicudata.so.70.1",
      "/tmp/linux/usr/lib/x86_64-linux-gnu/libssl.so.3",
      "/tmp/linux/usr/lib/x86_64-linux-gnu/libcrypto.so.3",
      "/tmp/linux/lib/x86_64-linux-gnu/libpthread.so.0",
      "/tmp/linux/usr/lib/x86_64-linux-gnu/libnuma.so.1",
      "/tmp/linux/usr/lib/x86_64-linux-gnu/libnuma.so.1.0.0",
      "/tmp/linux/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2"
    ],
    "MapDirs": {"publish/*": "/"},
    "Dirs": ["publish"],
    "Env": {
      "DOTNET_EnableDiagnostics": "0",
      "LD_LIBRARY_PATH": "/tmp/linux/lib:/tmp/linux/usr/lib:/tmp/linux/lib/x86_64-linux-gnu:/tmp/linux/usr/lib/x86_64-linux-gnu"
    }
}
```

There are few fixes in ops master branch, so until the next release, you can build from source:

```sh
$ git clone https://github.com/nanos/ops
$ cd ops
$ make deps build
$ export PATH=$(pwd):$PATH
```

Then publish the app and ran with ops:

```sh
$ cd ../myApp
$ dotnet publish -o dist -p:PublishSingleFile=true -c Release
$ ops run -c config.json dist/myApp 
```

**Comment by goncalo-oliveira** [comment]
Hi @am11 thank you for your reply and sorry for the delay.

I've tried using your setup, extracting files to an absolute `/tmp/linux` path and adding the `LD_LIBRARY_PATH`. I've also used the binary built from source and it seems to be giving more useful error messages. But unfortunately I still haven't succeeded

```
booting /Users/goncalo/.ops/images/myapp ...
en1: assigned 10.0.2.15
couldn't find program interpreter /lib64/ld-linux-x86-64.so.2
exit status 255
```

I've copied that `/lib64/ld-linux-x86-64.so.2` file from the ubuntu image and added it to the files list and referenced the path in the config. That leads to this

```bash
panic: failed building manifest: file "/tmp/rootfs/lib64/ld-linux-x86-64.so.2" is missing: stat /tmp/rootfs/lib64/ld-linux-x86-64.so.2: no such file or directory
```

The file, however, does exist... so unsure what's happening here.

```bash
$ ls /tmp/rootfs/lib64/ld-linux-x86-64.so.2                  
/tmp/rootfs/lib64/ld-linux-x86-64.so.2
```

```json
{
  "Files": [
    "/tmp/rootfs/lib/x86_64-linux-gnu/librt.so.1",
    "/tmp/rootfs/usr/lib/x86_64-linux-gnu/libicuuc.so.70.1",
    "/tmp/rootfs/usr/lib/x86_64-linux-gnu/libicui18n.so.70.1",
    "/tmp/rootfs/usr/lib/x86_64-linux-gnu/libicudata.so.70.1",
    "/tmp/rootfs/usr/lib/x86_64-linux-gnu/libssl.so.3",
    "/tmp/rootfs/usr/lib/x86_64-linux-gnu/libcrypto.so.3",
    "/tmp/rootfs/lib/x86_64-linux-gnu/libpthread.so.0",
    "/tmp/rootfs/usr/lib/x86_64-linux-gnu/libnuma.so.1",
    "/tmp/rootfs/usr/lib/x86_64-linux-gnu/libnuma.so.1.0.0",
    "/tmp/rootfs/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2",
    "/tmp/rootfs/lib64/ld-linux-x86-64.so.2"
  ],
  "MapDirs": {"published/*": "/" },
  "Env": {
    "COMPlus_EnableDiagnostics": "0",
    "DOTNET_EnableDiagnostics": "0",
    "LD_LIBRARY_PATH": "/tmp/rootfs/lib:/tmp/rootfs/usr/lib:/tmp/rootfs/lib/x86_64-linux-gnu:/tmp/rootfs/usr/lib/x86_64-linux-gnu:/tmp/rootfs/lib64"
  }
}
```

**Comment by am11** [comment]
The ops image creation step succeeded and now the error is at run-time (nanos). I forgot to link the issue: https://github.com/nanovms/nanos/issues/1810. ops now looks up the interpreter at custom LD_LIBRARY_PATH, but nanos does not.
