### ISSUE TITLE
Python3 package has socket issues

### ISSUE THREAD

**Issue by jasonrichardsmith** [nanovms/ops-examples#85]
I believe this is an issue with system sockets or possibly a missing library.
On this service:
https://github.com/GoogleCloudPlatform/microservices-demo/tree/master/src/emailservice

I followed the instructions found here:
https://github.com/nanovms/ops-examples/tree/master/python/python3.8

logger needs to be patched with the following patch, because the python app was built in 3.7:
```patch
@@ -33,7 +33,7 @@
 def getJSONLogger(name):
   logger = logging.getLogger(name)
   handler = logging.StreamHandler(sys.stdout)
-  formatter = CustomJsonFormatter('(timestamp) (severity) (name) (message)')
+  formatter = CustomJsonFormatter('%(timestamp)s %(level)s %(name)s %(message)s')
   handler.setFormatter(formatter)
   logger.addHandler(handler)
   logger.setLevel(logging.INFO)
```
It will work locally, but when loaded in ops with the following:
```bash
ops pkg load python_3.8.6 -c config.json -p 5055
```
```json
{
    "Env": {
	"PORT": "5055",
	"DISABLE_PROFILER": "1"
    },
    "Files": [
	    "email_server.py",
	    "email_client.py",
	    "logger.py",
	    "demo_pb2.py",
	    "demo_pb2_grpc.py"
    ],
    "MapDirs": {
        "./.venv/*": "/.local",
        "./usr/lib64/*": "/usr/lib/x86_64-linux-gnu"
    },
    "Dirs": [
	"templates"
    ],
    "Args": [
        "email_server.py"
    ]
}
```
```bash
tree usr
usr
└── lib64
    ├── librt.so.1
    └── libstdc++.so.6

1 directory, 2 files
```

I receive the following error:

```bash
booting /home/jason/.ops/images/python3 ...
en1: assigned 10.0.2.15
/.local/lib/python3.8/site-packages/googlecloudprofiler/client.py:167: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(self._profilers) is 0:
{"timestamp": 1642079157.4119132, "level": null, "name": "emailservice-server", "message": "starting the email service in dummy mode.", "severity": "INFO"}
{"timestamp": 1642079157.4135542, "level": null, "name": "emailservice-server", "message": "Profiler disabled.", "severity": "INFO"}
{"timestamp": 1642079157.4146888, "level": null, "name": "emailservice-server", "message": "Tracing enabled.", "severity": "INFO"}
en1: assigned FE80::D4BF:8FFF:FE65:9B4F
{"timestamp": 1642079166.4235234, "level": null, "name": "emailservice-server", "message": "Tracing disabled.", "severity": "INFO"}
E0113 13:06:06.438411677       1 cpu_linux.cc:50]            Cannot determine number of CPUs: assuming 1
epoll_ctl error: add: EPOLLEXCLUSIVE not supported
epoll_ctl error: add: EPOLLEXCLUSIVE not supported
{"timestamp": 1642079166.4669502, "level": null, "name": "emailservice-server", "message": "listening on port: 5055", "severity": "INFO"}
getsockopt error: getsockopt unimplemented optname: fd 5, level 1, optname 15
E0113 13:06:06.471703924       1 socket_utils_common_posix.cc:222] check for SO_REUSEPORT: {"created":"@1642079166.471676617","description":"No message of desired type","errno":42,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":201,"os_error":"No message of desired type","syscall":"getsockopt(SO_REUSEPORT)"}
E0113 13:06:06.476451652       1 server_chttp2.cc:40]        {"created":"@1642079166.476384756","description":"No address added out of total 1 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":306,"referenced_errors":[{"created":"@1642079166.476381574","description":"Failed to add any wildcard listeners","file":"src/core/lib/iomgr/tcp_server_posix.cc","file_line":340,"referenced_errors":[{"created":"@1642079166.476370547","description":"Unable to configure socket","fd":5,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":214,"referenced_errors":[{"created":"@1642079166.476366753","description":"Operation not supported","errno":95,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":242,"os_error":"Operation not supported","syscall":"getsockopt(TCP_NODELAY)"}]},{"created":"@1642079166.476380530","description":"Unable to configure socket","fd":5,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":214,"referenced_errors":[{"created":"@1642079166.476377900","description":"Operation not supported","errno":95,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":242,"os_error":"Operation not supported","syscall":"getsockopt(TCP_NODELAY)"}]}]}]}
Traceback (most recent call last):
  File "email_server.py", line 204, in <module>
    start(dummy_mode = True)
  File "email_server.py", line 139, in start
    server.add_insecure_port('[::]:'+port)
  File "/.local/lib/python3.8/site-packages/grpc/_server.py", line 961, in add_insecure_port
    return _common.validate_port_binding_result(
  File "/.local/lib/python3.8/site-packages/grpc/_common.py", line 166, in validate_port_binding_result
    raise RuntimeError(_ERROR_MESSAGE_PORT_BINDING_FAILED % address)
RuntimeError: Failed to bind to address [::]:5055; set GRPC_VERBOSITY=debug environment variable to see detailed error message.
```

**Comment by sanderssj** [comment]
Will be fixed by https://github.com/nanovms/nanos/pull/1652 which should allow the script to continue running.

**Comment by jasonrichardsmith** [comment]
I have tested this with nightly and received this response, no crash.

```
ops pkg load python_3.8.6 -c config.json -p 5055 -n
booting /home/jason/.ops/images/python3 ...
en1: assigned 10.0.2.15
/.local/lib/python3.8/site-packages/googlecloudprofiler/client.py:167: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(self._profilers) is 0:
{"timestamp": 1642495802.3567603, "level": null, "name": "emailservice-server", "message": "starting the email service in dummy mode.", "severity": "INFO"}
{"timestamp": 1642495802.3584683, "level": null, "name": "emailservice-server", "message": "Profiler disabled.", "severity": "INFO"}
{"timestamp": 1642495802.3595512, "level": null, "name": "emailservice-server", "message": "Tracing enabled.", "severity": "INFO"}
en1: assigned FE80::E4DD:3FF:FE7F:2C97
{"timestamp": 1642495811.368087, "level": null, "name": "emailservice-server", "message": "Tracing disabled.", "severity": "INFO"}
E0118 08:50:11.381410249       1 cpu_linux.cc:50]            Cannot determine number of CPUs: assuming 1
epoll_ctl error: add: EPOLLEXCLUSIVE not supported
epoll_ctl error: add: EPOLLEXCLUSIVE not supported
D0118 08:50:11.385200476       1 is_epollexclusive_available.cc:100] epoll_ctl with EPOLLEXCLUSIVE failed with error: 22. Not using epollex polling engine.
I0118 08:50:11.387306645       1 ev_epollex_linux.cc:1628]   Skipping epollex because it is not supported.
I0118 08:50:11.388679926       1 ev_epoll1_linux.cc:121]     grpc epoll fd: 3
D0118 08:50:11.389619546       1 ev_posix.cc:172]            Using polling engine: epoll1
D0118 08:50:11.392775896       1 lb_policy_registry.cc:42]   registering LB policy factory for "grpclb"
D0118 08:50:11.394432483       1 lb_policy_registry.cc:42]   registering LB policy factory for "priority_experimental"
D0118 08:50:11.395932129       1 lb_policy_registry.cc:42]   registering LB policy factory for "weighted_target_experimental"
D0118 08:50:11.397484248       1 lb_policy_registry.cc:42]   registering LB policy factory for "pick_first"
D0118 08:50:11.398973393       1 lb_policy_registry.cc:42]   registering LB policy factory for "round_robin"
D0118 08:50:11.400600650       1 lb_policy_registry.cc:42]   registering LB policy factory for "ring_hash_experimental"
D0118 08:50:11.402300731       1 dns_resolver_ares.cc:495]   Using ares dns resolver
D0118 08:50:11.405027894       1 certificate_provider_registry.cc:33] registering certificate provider factory for "file_watcher"
D0118 08:50:11.407161409       1 lb_policy_registry.cc:42]   registering LB policy factory for "cds_experimental"
D0118 08:50:11.408733743       1 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_impl_experimental"
D0118 08:50:11.410281070       1 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_resolver_experimental"
D0118 08:50:11.411934674       1 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_manager_experimental"
{"timestamp": 1642495811.4166017, "level": null, "name": "emailservice-server", "message": "listening on port: 5055", "severity": "INFO"}
E0118 08:50:11.418794691       1 socket_utils_common_posix.cc:223] check for SO_REUSEPORT: {"created":"@1642495811.418775855","description":"Failed to set SO_REUSEPORT","file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":205}
getsockopt error: getsockopt unimplemented optname: fd 5, level 6, optname 18
I0118 08:50:11.421888813       1 socket_utils_common_posix.cc:348] TCP_USER_TIMEOUT is not available. TCP_USER_TIMEOUT won't be used thereafter
```

**Comment by jasonrichardsmith** [comment]
I tested the service with grpcurl and the service responds and logs the request. This can be closed.
